- name: Create Provision user
  hosts: runtime
  vars:
    fluentd_name: td-agent
    fluentd_yum_lock_timeout: 30
    fluentd_plugins: []
    fluentd_groups: []
    fluentd_env: {}
  tasks:
    - name: fluentd | yum repo
      become: true
      copy:
        src: yum-reposd-fluentd.repo
        dest: /etc/yum.repos.d/fluentd.repo
        mode: 0644

    - name: fluentd | install
      become: true
      yum:
        name: "{{ fluentd_name }}"
        state: present
        lock_timeout: "{{ fluentd_yum_lock_timeout }}"

    - name: fluentd | add user to groups
      become: true
      user:
        name: td-agent
        append: true
        groups: "{{ item }}"
      with_items: "{{ fluentd_groups }}"

    - name: fluentd | configuration directory
      become: true
      file:
        path: /etc/{{ fluentd_name }}/conf.d
        state: directory
        mode: 0755

    - name: fluentd | main configuration
      become: true
      copy:
        src: fluentd.conf
        dest: /etc/{{ fluentd_name }}/{{ fluentd_name }}.conf
        mode: 0644

    - name: fluentd | list plugins
      command: /usr/sbin/td-agent-gem list
      register: _fluent_plugins
      changed_when: false
      check_mode: false

    - name: fluentd | install fluentd plugins
      become: true
      command: /usr/sbin/td-agent-gem install {{ item }}
      with_items: "{{ fluentd_plugins }}"
      when: item not in _fluent_plugins.stdout

    - name: fluentd | systemd configuration
      become: true
      file:
        path: /etc/systemd/system/{{ fluentd_name }}.service.d
        state: directory
        mode: 0755

    - name: fluentd | systemd configuration environment file
      become: true
      copy:
        src: systemd-fluentd-service-d-env.conf
        dest: /etc/systemd/system/{{ fluentd_name }}.service.d/50-env.conf
        mode: 0644

    - name: fluentd | start service
      become: true
      service:
        enabled: true
        name: "{{ fluentd_name }}"
        state: started